/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#eeeeee',
        'surface-variant': '#e2e2e2',
        'surface-container-low': '#f3f3f3',
        'primary-container': '#3b3b3b',
        surface: '#f9f9f9',
        'primary-fixed': '#5e5e5e',
        'surface-bright': '#f9f9f9',
        'secondary-fixed': '#c8c6c5',
        'on-primary-fixed': '#ffffff',
        'on-primary-fixed-variant': '#e2e2e2',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'on-primary': '#e2e2e2',
        'error-container': '#ffdad6',
        'secondary-container': '#d6d4d3',
        'surface-dim': '#dadada',
        'on-secondary-container': '#1c1b1b',
        'inverse-surface': '#303030',
        'surface-container-highest': '#e2e2e2',
        outline: '#777777',
        tertiary: '#3b3b3b',
        error: '#ba1a1a',
        'on-primary-container': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c6c6c6',
        'on-surface-variant': '#474747',
        'on-tertiary-container': '#ffffff',
        'on-surface': '#1b1b1b',
        background: '#f9f9f9',
        'surface-container-high': '#e8e8e8',
        'on-background': '#1b1b1b',
        primary: '#000000',
        'inverse-on-surface': '#f1f1f1',
        'surface-tint': '#5e5e5e',
        'on-error': '#ffffff',
        'inverse-primary': '#c6c6c6',
        'on-error-container': '#410002',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
